id = "noteboks"
name = "Noteboks"
version = "0.0.1"
schema_version = 1
authors = ["Zac Garby <me@zacgarby.co.uk"]
description = "Noteboks support for Zed. A fork of zed-org."
repository = "https://github.com/zac-garby/noteboks"

[grammars.org]
repository = "https://github.com/milisims/tree-sitter-org"
commit = "64cfbc213f5a83da17632c95382a5a0a2f3357c1"
