id = "noteboks"
name = "noteboks"
version = "0.0.1"
schema_version = 1
authors = ["Zac Garby <me@zacgarby.co.uk"]
description = "Noteboks support for Zed. A fork of zed-org."
repository = "https://github.com/zac-garby/noteboks"

[grammars.org]
repository = "https://github.com/zac-garby/tree-sitter-org"
commit = "2d8068efcb63c4a556e1676db61ea278ce2522ef"

[language_servers.noteboks]
name = "Noteboks LSP"
languages = ["noteboks"]
