id = "noteboks"
name = "noteboks"
version = "0.0.1"
schema_version = 1
authors = ["Zac Garby <me@zacgarby.co.uk"]
description = "Noteboks support for Zed. A fork of zed-org."
repository = "https://github.com/zac-garby/noteboks"

[grammars.org]
repository = "https://github.com/zac-garby/tree-sitter-org"
commit = "770aceb0a18608d27342d8b1a34e839c0d927f53"

[language_servers.noteboks]
name = "Noteboks LSP"
languages = ["noteboks"]
